### ISSUE TITLE
ctrl-shift-T conflicts with builtin keymap for reopen-closed-item on non-mac platforms

### ISSUE THREAD

**Issue by forivall** [boogie666/atom-mocha#1]
Guh. It needs to be changed, I would use `alt-shift-T`

**Comment by boogie666** [comment]
You can disable the key bindings for atom-mocha, just like any other package in atom. 

Just go into the Packages/Atom Mocha, in the "Keybindings" section and un-tic the enable button. 
This will disable all binding for atom mocha, you can then rebind the keys in your keymap.cson file anyway you see fit.

I won't change this because i like using ctrl+shift-T, and its easy for anyone to bind his own stuff anyway.

**Comment by forivall** [comment]
Are you on a Mac? (Y/N)

I know you can disable it. Of course that's what I did. But there's no reason to override default keybindings.

**Comment by boogie666** [comment]
No (i'm on windows) you do have a point, my personal prefs should not matter in this case. i'll fix this later today as you suggest (using alt+shift+T) and push a new release.

**Comment by boogie666** [comment]
as of version 0.0.4 this is fixed cheers :)

**Comment by forivall** [comment]
Thanks! Sorry for being blunt, I was impaired while writing my response to your initial "close" and didn't realise that my initial comment didn't really say much.
