### ISSUE TITLE
support for different transpilers (coffeescript)

### ISSUE THREAD

**Issue by slvnperron** [boogie666/atom-mocha#2]

**Comment by boogie666** [comment]
Not a bad idea :P i'll look into it.

**Comment by boogie666** [comment]
I've added support for coffeescript. as of v0.0.3 there is an option in Packages/Atom Mocha for what compiler atom-mocha should use, Nothing, Babel or Coffeescript. Default is set to ES6 (Babel) to not break anything. For now after you change this setting please restart Atom. otherwise changes will not take effect.

**Comment by slvnperron** [comment]
Awesome thanks !
