### ISSUE TITLE
upgrade to babel 6

### ISSUE THREAD

**Issue by flying-sheep** [boogie666/atom-mocha#7]
babel 5 doesn’t work for me here:

[this line](https://github.com/babel/babel/blob/5.x/packages/babel/src/api/register/node.js#L76) in api/node.js does `var optsManager = new OptionManager;`

this calls the [constructor](https://github.com/babel/babel/blob/5.x/packages/babel/src/transformation/file/options/option-manager.js#L28) which does `constructor(log, pipeline) { […] this.log = log; }`, so `optsManager.log === undefined`

the [next line](https://github.com/babel/babel/blob/5.x/packages/babel/src/api/register/node.js#L77) in api/node.js now does `optsManager.mergeOptions(transformOpts);`

however, [mergeOptions uses `this.log`](https://github.com/babel/babel/blob/5.x/packages/babel/src/transformation/file/options/option-manager.js#L85) if any option is set to a falsy value.

in my case this is due to some .babelrc interfering or whatever, so it crashes -.-

**Comment by boogie666** [comment]
I've tried to upgrade to babel 6, but due to the the way atom mocha works i can't switch atm.
Currently i use the in memory version of the compiler, i.e. require("babel/register").

Babel 6 has this option but it's really slow... Babel 5 is much faster so until babel 6 becomes fast, won't switch.

Cheers,
Boogie
